# Generated by Django 5.2.17 on 2026-09-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Tanggal pembelian')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total nilai pembelian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='parties.supplier')),
            ],
            options={
                'verbose_name': 'Pembelian',
                'verbose_name_plural': 'Pembelian',
                'ordering': ['-date', '-purchase_id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('purchase_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah dibeli')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga beli per unit')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='catalog.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Detail Pembelian',
                'verbose_name_plural': 'Detail Pembelian',
                'ordering': ['purchase_item_id'],
            },
        ),
    ]
