# Generated by Django 5.2.17 on 2026-09-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode akun')),
                ('name', models.CharField(max_length=200, verbose_name='Nama akun')),
                ('account_type', models.CharField(choices=[('asset', 'Aset'), ('liability', 'Kewajiban'), ('equity', 'Ekuitas'), ('revenue', 'Pendapatan'), ('expense', 'Beban')], max_length=20, verbose_name='Tipe akun')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Daftar Akun',
                'verbose_name_plural': 'Daftar Akun',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('journal_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Tanggal jurnal')),
                ('description', models.CharField(max_length=255, verbose_name='Keterangan')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kredit')),
                ('reference_type', models.CharField(blank=True, choices=[('sale', 'Penjualan'), ('purchase', 'Pembelian'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='Tipe referensi')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID referensi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnal',
                'ordering': ['-date', '-journal_entry_id'],
            },
        ),
    ]
