# Generated by Django 5.2.17 on 2026-09-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama barang')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga jual')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga beli')),
                ('has_expiry', models.BooleanField(default=False, verbose_name='Punya kadaluarsa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_code', models.CharField(blank=True, max_length=100, verbose_name='Kode batch')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Tanggal kadaluarsa')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Jumlah stok dalam batch')),
                ('received_date', models.DateField(verbose_name='Tanggal barang masuk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Batch Barang',
                'verbose_name_plural': 'Batch Barang',
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_available', models.PositiveIntegerField(default=0, verbose_name='Jumlah stok tersedia')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokasi penyimpanan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rows', to='catalog.product')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rows', to='catalog.productbatch')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stok',
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'batch'), name='unique_inventory_product_batch')],
            },
        ),
    ]
