# Generated by Django 5.2.17 on 2026-09-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Masuk'), ('out', 'Keluar')], max_length=10, verbose_name='Tipe mutasi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('reference_type', models.CharField(choices=[('sale', 'Penjualan'), ('purchase', 'Pembelian'), ('initial', 'Stok Awal'), ('adjustment', 'Penyesuaian'), ('cancel', 'Pembatalan')], default='initial', max_length=20, verbose_name='Tipe referensi')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID referensi')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='catalog.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Mutasi Stok',
                'verbose_name_plural': 'Mutasi Stok',
                'ordering': ['-date', '-movement_id'],
            },
        ),
    ]
