# Generated by Django 5.2.17 on 2026-09-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Tanggal transaksi')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total nilai penjualan')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('e-wallet', 'E-Wallet')], default='cash', max_length=20, verbose_name='Metode pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='parties.customer')),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Penjualan',
                'ordering': ['-date', '-sale_id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('sale_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah terjual')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga per unit')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total harga item')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='catalog.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Detail Penjualan',
                'verbose_name_plural': 'Detail Penjualan',
                'ordering': ['sale_item_id'],
            },
        ),
    ]
